In [1]:
import Mortgage_schedules as ms
import os
import json
import pandas as pd
import plotly.express as px
from importlib import reload # reloads the module if you made changes

In [12]:
mike = 1185.25*2
emily =255*2
extra_payment = mike+emily 
extra_payment

2880.5

In [2]:
# reload(ms)

In [3]:
# Load schedules
l = open('loans.json')
loans = json.load(l)
schedules = {}
for m in loans:
    schedules[m]= ms.get_schedules(loans[m])

In [51]:
# loans['BrierRose']

In [139]:
# # Scenario 1
# payoff_first = MortName # string 
# cashflow_4_new_payoff =  # boolean apply old total payment to new mortgage extra payment
# newdraw = # boolean  if heloc redraw to apply to lump sum on another mortgage
# newdraw_amt = # int dollar amount to draw
# payoff_second = MortName # string
# payoff_third = MortName # string
# payoff_fourth = MortName # string

5

In [233]:
userinput_box_1 = 'Heloc'
userinput_box_1_apply_cf = True
userinput_box_1_newdraw = True
userinput_box_1_newdraw_amt = 60000.00
userinput_box_2 = 'BrierRose'
userinput_box_2_apply_cf = True
userinput_box_3 = 'Turnstone'
userinput_box_3_apply_cf = True

In [16]:
scenario = {}
scenario['1'] = {
    "Name":'Heloc',
    "Initial_Extra":2880.50,
    "Scenario_start_dt":'12-01-2022',
    "Apply_CF" : True,
    "NewDraw" : False,
    "NewDraw_amt" : 60000.00,
    "Lump" : False,
    "Lump_amt" : None
}
scenario['2'] = {
    "Name":'BrierRose',
    "Initial_Extra":None,
    "Scenario_start_dt":None,
    "Apply_CF" : True,
    "NewDraw" : False,
    "NewDraw_amt" : None,
    "Lump" : True,
    "Lump_amt" : 60000.00
}
scenario['3'] = {
    "Name":'Turnstone',
    "Initial_Extra":None,
    "Scenario_start_dt":None,
    "Apply_CF" : True,
    "NewDraw" : False,
    "NewDraw_amt" : None,
    "Lump" : False,
    "Lump_amt" : None
}
scenario['4'] = {
    "Name":'LakeSide',
    "Initial_Extra":None,
    "Scenario_start_dt":None,
    "Apply_CF" : False,
    "NewDraw" : False,
    "NewDraw_amt" : None,
    "Lump" : False,
    "Lump_amt" : None
}

# Run Scenario 1

In [29]:
df = schedules[scenario['1']['Name']]
date = scenario['1']['Scenario_start_dt']
extra_payment = scenario['1']['Initial_Extra']
interest = loans[scenario['1']['Name']]['interest']
payments_year = loans[scenario['1']['Name']]['payments_year']
morgterm = loans[scenario['1']['Name']]['term']
lump = None
# if userinput_box_1_apply_cf:
#     lump=[date,userinput_box_1_newdraw_amt]

In [30]:
p1=add_extra_pay(df,date, extra_payment, interest, payments_year,morgterm,lump)

In [34]:
# p1[2]

# Run Scenario 2

In [54]:
if scenario['2']['Lump']:
    lump = (date,scenario['2']['Lump_amt'])
    print(lump)

('11-01-2025', 60000.0)

In [96]:
# use cashflow from previous payoff
if scenario['2']['Apply_CF']:
    date=p1[0].strftime('%m-%d-%Y')
    extra_payment=p1[1]
if scenario['2']['Lump']:
    lump = (date,scenario['2']['Lump_amt'])
df = schedules[scenario['2']['Name']]
interest = loans[scenario['2']['Name']]['interest']
payments_year = loans[scenario['2']['Name']]['payments_year']
morgterm = loans[scenario['2']['Name']]['term']

In [97]:
lump

('11-01-2025', 60000.0)

In [110]:
period = 57
start_date = 57

In [111]:
check_lump(period, start_date, extra_payment, lump)

lump period
57

60000.0

In [120]:
p2=add_extra_pay(df,date, extra_payment, interest, payments_year,morgterm,lump)

KeyError: 0

In [115]:
p2[2][55:100]
# p2[2]

,Payment Date,Org Total Payment,Total Payment,Interest,Principal,Additional Payment,Org Ending Balance,Ending Balance
Period,,,,,,,,
56,2025-10-01,1226.91,1226.91,705.96,520.94,0.0,250487.65,250487.65
57,2025-11-01,1226.91,61226.91,704.50,522.41,60000.0,249965.24,189965.24
58,2025-12-01,1226.91,61226.91,703.03,523.88,60000.0,249441.36,129441.36
59,2026-01-01,1226.91,61226.91,701.55,525.36,60000.0,248916.00,68916.00
60,2026-02-01,1226.91,61226.91,700.08,526.83,60000.0,248389.17,8389.17
61,2026-03-01,1226.91,61226.91,698.59,528.32,60000.0,247860.85,0.00

In [ ]:
scenarios.keys().sort() # will maintain order

In [ ]:
# this is what needs to be ran for each scenrio
p1=add_extra_pay(df,date, extra_payment, interest, payments_year,morgterm,lump)

# dynamic extra payment
Figure out how to inject an additional payment into existing schedule

In [203]:
df=schedules[userinput_box_1]
interest =loans[userinput_box_1]['interest']
payments_year = loans[userinput_box_1]['payments_year']
mike = 1185.25*2
emily =255*2
extra_payment = mike+emily 
date = '2022-12-01'
morgterm=loans[userinput_box_1]['term']

In [211]:
p1=add_extra_pay(df,date, extra_payment, interest, payments_year,morgterm)

In [230]:
p1[0].strftime("%Y-%m-%d")

'2025-11-01'

In [241]:
df=schedules[userinput_box_2]
interest =loans[userinput_box_2]['interest']
payments_year = loans[userinput_box_2]['payments_year']
morgterm=loans[userinput_box_2]['term']

if userinput_box_1_apply_cf:
    extra_payment = p1[1]
    old_end = {"year":p1[0].strftime("%Y"),"month":p1[0].strftime("%m"),"day":p1[0].strftime("%d")}
    date =old_end["year"]+'-'+str(int(old_end["month"])+1)+'-'+old_end["day"]
if userinput_box_1_apply_cf:
    lump=[date,userinput_box_1_newdraw_amt]

In [258]:
# Python optional arguments with default argument
def main(num1, num2, num3 = 0):
    # return the sum of the arguments
    return num1+num2 +num3
# calling the function with two arguments
print("the sum is: " ,main(10,5))

the sum is:  15

In [91]:
p2=add_extra_pay(df,date, extra_payment, interest, payments_year,morgterm,lump)

lump apply date: 11-01-2025

In [92]:
p2[2][50:60]

,Payment Date,Org Total Payment,Total Payment,Interest,Principal,Additional Payment,Org Ending Balance,Ending Balance
Period,,,,,,,,
51,2025-05-01,1226.91,1226.91,713.23,513.68,0.0,253077.79,253077.79
52,2025-06-01,1226.91,1226.91,711.78,515.12,0.0,252562.67,252562.67
53,2025-07-01,1226.91,1226.91,710.33,516.57,0.0,252046.10,252046.10
54,2025-08-01,1226.91,1226.91,708.88,518.03,0.0,251528.07,251528.07
55,2025-09-01,1226.91,1226.91,707.42,519.48,0.0,251008.59,251008.59
56,2025-10-01,1226.91,1226.91,705.96,520.94,0.0,250487.65,250487.65
57,2025-11-01,1226.91,61226.91,704.50,522.41,60000.0,249965.24,189965.24
58,2025-12-01,1226.91,61226.91,703.03,523.88,60000.0,249441.36,129441.36
59,2026-01-01,1226.91,61226.91,701.55,525.36,60000.0,248916.00,68916.00
60,2026-02-01,1226.91,61226.91,700.08,526.83,60000.0,248389.17,8389.17

In [202]:

#     # scenario 2
# start_rent = None 
# start_cash_flow = None
# rent_increase_yoy = None
# extra_payment_prct = None
# initial_additional_pmt = extra_payment

In [114]:
schedules.keys()

dict_keys(['Turnstone', 'Heloc', 'LakeSide', 'BrierRose'])

In [156]:
df=schedules['BrierRose']
interest =loans['BrierRose']['interest']
payments_year = loans['BrierRose']['payments_year']
extra_payment = 1000
date = '2022-12-01'

In [167]:
final=add_extra_pay(df,start_date, extra_payment, interest, payments_year)

# Extra payment to heloc

'int_only'

In [201]:
df=schedules['Heloc']
interest =loans['Heloc']['interest']
payments_year = loans['Heloc']['payments_year']
mike = 1185.25*2
emily =255*2
extra_payment = mike+emily 
date = '2022-12-01'
morgterm=loans['Heloc']['term']

In [200]:
p1=add_extra_pay(df,start_date, extra_payment, interest, payments_year,morgterm)

In [ ]:
df=schedules['Heloc']
interest =loans['Heloc']['interest']
payments_year = loans['Heloc']['payments_year']

In [252]:
# help(add_extra_pay())

In [107]:
def check_lump(period, start_date, extra_payment, lump):
    p_amt = extra_payment
    if lump == None:
        pass
    elif period == start_date:
        print("lump period")
        print(str(period))
        p_amt = lump[1]

    return p_amt

In [140]:
def add_extra_pay(df,date, extra_payment, interest, payments_year, morgterm, lump = None):
    initial_pmt=df.loc[1,'Org Total Payment']
    start_date = df[df['Payment Date'] == date].index[0]
    
#     period_additional_pmt = extra_payment
    
    for period in range(1, len(df)+1):
        print(str(period))
        if period == start_date:
            if lump != None:
                if period == lump[0]:
                    print("lump apply date: "+ str(lump[0]))
                    period_additional_pmt = lump[1]
                else:
                    period_additional_pmt = extra_payment

            for p in range(period, len(df)+1):  
                period_additional_pmt = check_lump(p, start_date, extra_payment, lump)
                # get the prior period values 
                previous_total_payments = df.loc[p-1,'Total Payment']
                previous_principal = df.loc[period-1,'Principal']
                previous_org_ending_balance = df.loc[p-1,'Org Ending Balance']
                previous_ending_balance = df.loc[p-1,'Ending Balance']
                previous_= df.loc[p-1,'Total Payment']

                # Calculate remainder values to get the end of loan bal
                period_interest = previous_org_ending_balance * interest / payments_year
                if morgterm == 'int_only':
                    period_principal = 0.0
                else:
                    period_principal = initial_pmt - period_interest
                    
                org_ending_balance = previous_org_ending_balance - period_principal
                ending_balance = previous_ending_balance - period_principal - period_additional_pmt
                org_ending_balance = 0 if org_ending_balance <= 0 else org_ending_balance
                ending_balance = 0 if ending_balance <= 0 else ending_balance

                row_dict ={
                'Org Total Payment': initial_pmt,
                'Total Payment': initial_pmt + period_additional_pmt,
                'Interest': period_interest,
                'Principal': period_principal,
                'Additional Payment': period_additional_pmt, 
                'Org Ending Balance': org_ending_balance,
                'Ending Balance': ending_balance
                }

                columns = list(row_dict.keys())
                period_values = list(row_dict.values())
                df.loc[p, columns] = period_values
                df = df.round(2)
    end_date = df[df['Ending Balance'] == 0.00].index[0]
    payoff_date=df.loc[end_date,'Payment Date']
    avail_cashflow=df.loc[end_date,'Total Payment']
    final_df = df[:end_date]
    return payoff_date, avail_cashflow,final_df

In [121]:
# use cashflow from previous payoff
if scenario['2']['Apply_CF']:
    date=p1[0].strftime('%m-%d-%Y')
    extra_payment=p1[1]
if scenario['2']['Lump']:
    lump = (date,scenario['2']['Lump_amt'])
df = schedules[scenario['2']['Name']]
interest = loans[scenario['2']['Name']]['interest']
payments_year = loans[scenario['2']['Name']]['payments_year']
morgterm = loans[scenario['2']['Name']]['term']

In [141]:
p2=add_extra_pay(df,date, extra_payment, interest, payments_year,morgterm,lump)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
lump period
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360

In [143]:
p2[2]

,Payment Date,Org Total Payment,Total Payment,Interest,Principal,Additional Payment,Org Ending Balance,Ending Balance
Period,,,,,,,,
1,2021-03-01,1226.91,1226.91,780.53,446.38,0.00,277073.62,277073.62
2,2021-04-01,1226.91,1226.91,779.27,447.64,0.00,276625.98,276625.98
3,2021-05-01,1226.91,1226.91,778.01,448.89,0.00,276177.09,276177.09
4,2021-06-01,1226.91,1226.91,776.75,450.16,0.00,275726.93,275726.93
5,2021-07-01,1226.91,1226.91,775.48,451.42,0.00,275275.51,275275.51
...,...,...,...,...,...,...,...,...
101,2029-07-01,1226.91,4665.58,635.78,591.13,3438.67,225464.05,14162.57
102,2029-08-01,1226.91,4665.58,634.12,592.79,3438.67,224871.26,10131.11
103,2029-09-01,1226.91,4665.58,632.45,594.46,3438.67,224276.80,6097.98
104,2029-10-01,1226.91,4665.58,630.78,596.13,3438.67,223680.67,2063.18
105,2029-11-01,1226.91,4665.58,629.10,597.81,3438.67,223082.86,0.00

In [54]:
for period in range(1, len(df)+1):
            # get the prior period values 

    previous_total_payments = df.loc[period-1,'Total Payment']
    previous_principal = df.loc[period-1,'Principal']
    previous_org_ending_balance = df.loc[period-1,'Org Ending Balance']
    previous_ending_balance = df.loc[period-1,'Ending Balance']
    previous_= df.loc[period-1,'Total Payment']

KeyError: 0

In [45]:
loans['BrierRose']

{'interest': 0.03375,
 'years': 30,
 'payments_year': 12,
 'mortgage': 277520.0,
 'start_date': '2021-03-01',
 'Current_payment': 1767.56,
 'HOA_club': 161.25,
 'HOA_resort': 204.0,
 'escrow': 540.65,
 'term': 'full'}

In [53]:
interest =loans['BrierRose']['interest']
payments_year = loans['BrierRose']['payments_year']
initial_pmt = df.loc[period-1,'Org Total Payment']

KeyError: 0

In [57]:
# Calculate remainder values to get the end of loan bal
period_interest = previous_org_ending_balance * interest / payments_year
period_principal = initial_pmt - period_interest
org_ending_balance = previous_org_ending_balance - period_principal
ending_balance = previous_ending_balance - period_principal - period_additional_pmt
org_ending_balance = 0 if org_ending_balance <= 0 else org_ending_balance
ending_balance = 0 if ending_balance <= 0 else ending_balance

In [60]:
        row_dict ={
        'Org Total Payment': initial_pmt,
        'Total Payment': initial_pmt + period_additional_pmt,
        'Interest': period_interest,
        'Principal': period_principal,
        'Additional Payment': period_additional_pmt, 
        'Org Ending Balance': org_ending_balance,
        'Ending Balance': ending_balance
        }
        columns = list(row_dict.keys())
        period_values = list(row_dict.values())
        df.loc[period, columns] = period_values
        df = df.round(2)

In [61]:
row_dict

{'Org Total Payment': 760.6,
 'Total Payment': 1760.6,
 'Interest': 185.28353437500002,
 'Principal': 575.316465625,
 'Additional Payment': 1000,
 'Org Ending Balance': 65303.273534374996,
 'Ending Balance': 64303.273534374996}